spring:
  application:
    name: task-service
  config:
    import: "optional:configserver:http://localhost:8008"

  main:
    allow-bean-definition-overriding: true


  #r2dbc (database webflux)
  r2dbc:
    url: r2dbc:pool:postgresql://localhost:2347/task_db
    password: task
    username: task
server:
  port: 8081



#  security grant_type (client_credentials)
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          jwk-set-uri: http://localhost:8888/auth/realms/mini/protocol/openid-connect/certs
#          issuer-uri: http://localhost:8800/auth/realms/mini