spring:
  application:
    name: task-service
  config:
    import: "optional:configserver:http://localhost:8008"

  main:
    allow-bean-definition-overriding: true

  #r2dbc (database webflux)
  r2dbc:
    url: r2dbc:pool:postgresql://localhost:2347/task_db
    password: task
    username: task
server:
  port: 8081


  springdoc:
    packagesToScan: com.ksga.service.task
