server:
  port: 8008

# config config-server to git
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          skip-ssl-validation : true
          uri: https://gitlab.com/RITH10th/config-server #config-server (name repository git)
          default-label: master   #default of git

