server:
  port: 8008
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kimhab11/config-server-file
          default-label: master